version: "3.9"
services:
  frigate:
    container_name: frigate
    privileged: true # this may not be necessary for all setups
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:${VERSION:-stable}
    shm_size: ${SHM_SIZE:-64mb}
    devices:
      - /dev/bus/usb:/dev/bus/usb # passes the USB Coral
      - /dev/dri/renderD128 # for intel hwaccel, needs to be updated for your hardware
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      TZ: Europe/Amsterdam
      FRIGATE_RTSP_PASSWORD: "${RTSP_PASSWORD:-password}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .config/config.yml:/config/config.yml
      - ${STORAGE_PATH:?path must be defined}:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock